### Получить корзину продуктов
GET http://localhost:8080//shoppingCart/get

### Добавить продукт 1
POST http://localhost:8080//shoppingCart/add
Content-Type: application/json

{
  "id": 13
}

### Добавить продукт 2
POST http://localhost:8080//shoppingCart/add
Content-Type: application/json

{
  "id": 56
}

### Добавить продукт 3
POST http://localhost:8080//shoppingCart/add
Content-Type: application/json

{
  "id": 44
}